// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugrxadnztbkkbmgbwmfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVncnhhZG56dGJra2JtZ2J3bWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MDQ3MjYsImV4cCI6MjA2Njk4MDcyNn0.mbMxwZGPyVF2kJImxNxngp7OSYzyhzjtZekGTzxkek0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});